-- =========================================================
-- Supabase bootstrap schema for a fresh project
-- Run this in the SQL editor of the new Supabase account.
-- =========================================================

begin;

create extension if not exists pgcrypto;

-- ---------------------------------------------------------
-- Tables
-- ---------------------------------------------------------

create table if not exists public.portfolio_messages (
    id bigint generated by default as identity primary key,
    content text not null,
    timestamp text,
    user_agent text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table if not exists public.portfolio_notes (
    id bigint generated by default as identity primary key,
    content text not null,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table if not exists public.portfolio_deadlines (
    id bigint generated by default as identity primary key,
    description text not null,
    deadline_date date not null,
    deadline_time time without time zone,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- ---------------------------------------------------------
-- Indexes
-- ---------------------------------------------------------

create index if not exists portfolio_messages_created_at_idx
    on public.portfolio_messages (created_at desc);

create index if not exists portfolio_notes_created_at_idx
    on public.portfolio_notes (created_at desc);

create index if not exists portfolio_deadlines_deadline_date_idx
    on public.portfolio_deadlines (deadline_date asc);

-- ---------------------------------------------------------
-- Grants
-- ---------------------------------------------------------

grant usage on schema public to anon, authenticated, service_role;
grant usage, select on all sequences in schema public to anon, authenticated, service_role;

grant insert on table public.portfolio_messages to anon, authenticated;
grant select, delete on table public.portfolio_messages to authenticated, service_role;

grant select, insert, update, delete on table public.portfolio_notes to authenticated, service_role;
grant select, insert, update, delete on table public.portfolio_deadlines to authenticated, service_role;

-- ---------------------------------------------------------
-- Row Level Security
-- ---------------------------------------------------------

alter table public.portfolio_messages enable row level security;
alter table public.portfolio_notes enable row level security;
alter table public.portfolio_deadlines enable row level security;
-- Clear older policy names so reruns stay safe.
drop policy if exists "Allow internal insert" on public.portfolio_messages;
drop policy if exists "Allow internal select" on public.portfolio_messages;
drop policy if exists "Allow internal delete" on public.portfolio_messages;
drop policy if exists "Enable insert for everyone" on public.portfolio_messages;
drop policy if exists "Enable read access for authenticated users only" on public.portfolio_messages;
drop policy if exists "Enable delete access for authenticated users only" on public.portfolio_messages;
drop policy if exists "portfolio_messages_public_insert" on public.portfolio_messages;
drop policy if exists "portfolio_messages_authenticated_select" on public.portfolio_messages;
drop policy if exists "portfolio_messages_authenticated_delete" on public.portfolio_messages;

drop policy if exists "Allow select for authenticated users" on public.portfolio_notes;
drop policy if exists "Allow insert for authenticated users" on public.portfolio_notes;
drop policy if exists "Allow delete for authenticated users" on public.portfolio_notes;
drop policy if exists "Allow update for authenticated users" on public.portfolio_notes;
drop policy if exists "portfolio_notes_authenticated_select" on public.portfolio_notes;
drop policy if exists "portfolio_notes_authenticated_insert" on public.portfolio_notes;
drop policy if exists "portfolio_notes_authenticated_update" on public.portfolio_notes;
drop policy if exists "portfolio_notes_authenticated_delete" on public.portfolio_notes;

drop policy if exists "Allow select for authenticated users" on public.portfolio_deadlines;
drop policy if exists "Allow insert for authenticated users" on public.portfolio_deadlines;
drop policy if exists "Allow delete for authenticated users" on public.portfolio_deadlines;
drop policy if exists "Allow update for authenticated users" on public.portfolio_deadlines;
drop policy if exists "portfolio_deadlines_authenticated_select" on public.portfolio_deadlines;
drop policy if exists "portfolio_deadlines_authenticated_insert" on public.portfolio_deadlines;
drop policy if exists "portfolio_deadlines_authenticated_update" on public.portfolio_deadlines;
drop policy if exists "portfolio_deadlines_authenticated_delete" on public.portfolio_deadlines;

create policy "portfolio_messages_public_insert"
on public.portfolio_messages
for insert
to public
with check (true);

create policy "portfolio_messages_authenticated_select"
on public.portfolio_messages
for select
to authenticated
using (true);

create policy "portfolio_messages_authenticated_delete"
on public.portfolio_messages
for delete
to authenticated
using (true);

create policy "portfolio_notes_authenticated_select"
on public.portfolio_notes
for select
to authenticated
using (true);

create policy "portfolio_notes_authenticated_insert"
on public.portfolio_notes
for insert
to authenticated
with check (true);

create policy "portfolio_notes_authenticated_update"
on public.portfolio_notes
for update
to authenticated
using (true)
with check (true);

create policy "portfolio_notes_authenticated_delete"
on public.portfolio_notes
for delete
to authenticated
using (true);

create policy "portfolio_deadlines_authenticated_select"
on public.portfolio_deadlines
for select
to authenticated
using (true);

create policy "portfolio_deadlines_authenticated_insert"
on public.portfolio_deadlines
for insert
to authenticated
with check (true);

create policy "portfolio_deadlines_authenticated_update"
on public.portfolio_deadlines
for update
to authenticated
using (true)
with check (true);

create policy "portfolio_deadlines_authenticated_delete"
on public.portfolio_deadlines
for delete
to authenticated
using (true);

commit;
