-- =========================================================
-- Supabase bootstrap schema for a fresh project
-- Run this in the SQL editor of the new Supabase account.
-- =========================================================

begin;

create extension if not exists pgcrypto;

-- ---------------------------------------------------------
-- Tables
-- ---------------------------------------------------------

create table if not exists public.portfolio_messages (
    id bigint generated by default as identity primary key,
    content text not null,
    timestamp text,
    user_agent text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table if not exists public.portfolio_notes (
    id bigint generated by default as identity primary key,
    content text not null,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table if not exists public.portfolio_deadlines (
    id bigint generated by default as identity primary key,
    description text not null,
    deadline_date date not null,
    deadline_time time without time zone,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table if not exists public.blog_subscribers (
    id bigint generated by default as identity primary key,
    email text not null,
    source text default 'blogs_page',
    user_agent text,
    is_active boolean default true not null,
    unsubscribe_token text,
    unsubscribed_at timestamp with time zone,
    subscribed_at timestamp with time zone default timezone('utc'::text, now()) not null,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.blog_subscribers
    add column if not exists is_active boolean default true not null,
    add column if not exists unsubscribe_token text,
    add column if not exists unsubscribed_at timestamp with time zone;

update public.blog_subscribers
set
    is_active = coalesce(is_active, true),
    unsubscribe_token = coalesce(unsubscribe_token, gen_random_uuid()::text)
where is_active is null or unsubscribe_token is null;

alter table public.blog_subscribers
    alter column is_active set default true,
    alter column is_active set not null;

create table if not exists public.blog_newsletter_campaigns (
    post_id text primary key,
    post_title text not null,
    post_url text not null,
    post_date timestamp with time zone,
    status text default 'pending' not null,
    subscriber_count integer default 0 not null,
    sent_count integer default 0 not null,
    deployment_url text,
    commit_sha text,
    last_error text,
    first_attempt_at timestamp with time zone,
    last_attempt_at timestamp with time zone,
    completed_at timestamp with time zone,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table if not exists public.blog_newsletter_deliveries (
    id bigint generated by default as identity primary key,
    post_id text not null references public.blog_newsletter_campaigns (post_id) on delete cascade,
    subscriber_email text not null,
    unsubscribe_token_snapshot text not null,
    status text default 'pending' not null,
    resend_email_id text,
    last_error text,
    sent_at timestamp with time zone,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
    unique (post_id, subscriber_email)
);

-- ---------------------------------------------------------
-- Indexes
-- ---------------------------------------------------------

create unique index if not exists blog_subscribers_email_key
    on public.blog_subscribers (email);

create unique index if not exists blog_subscribers_unsubscribe_token_key
    on public.blog_subscribers (unsubscribe_token);

create index if not exists portfolio_messages_created_at_idx
    on public.portfolio_messages (created_at desc);

create index if not exists portfolio_notes_created_at_idx
    on public.portfolio_notes (created_at desc);

create index if not exists portfolio_deadlines_deadline_date_idx
    on public.portfolio_deadlines (deadline_date asc);

create index if not exists blog_subscribers_created_at_idx
    on public.blog_subscribers (created_at desc);

create index if not exists blog_subscribers_is_active_idx
    on public.blog_subscribers (is_active, subscribed_at desc);

create index if not exists blog_newsletter_campaigns_status_idx
    on public.blog_newsletter_campaigns (status, created_at desc);

create index if not exists blog_newsletter_deliveries_status_idx
    on public.blog_newsletter_deliveries (post_id, status, created_at desc);

-- ---------------------------------------------------------
-- Grants
-- ---------------------------------------------------------

grant usage on schema public to anon, authenticated, service_role;
grant usage, select on all sequences in schema public to anon, authenticated, service_role;

grant insert on table public.portfolio_messages to anon, authenticated;
grant select, delete on table public.portfolio_messages to authenticated, service_role;

grant select, insert, update, delete on table public.portfolio_notes to authenticated, service_role;
grant select, insert, update, delete on table public.portfolio_deadlines to authenticated, service_role;

grant insert on table public.blog_subscribers to anon, authenticated;
grant select, update, delete on table public.blog_subscribers to authenticated, service_role;
grant select on table public.blog_newsletter_campaigns to authenticated, service_role;
grant insert, update, delete on table public.blog_newsletter_campaigns to service_role;
grant select on table public.blog_newsletter_deliveries to authenticated, service_role;
grant insert, update, delete on table public.blog_newsletter_deliveries to service_role;

-- ---------------------------------------------------------
-- Row Level Security
-- ---------------------------------------------------------

alter table public.portfolio_messages enable row level security;
alter table public.portfolio_notes enable row level security;
alter table public.portfolio_deadlines enable row level security;
alter table public.blog_subscribers enable row level security;
alter table public.blog_newsletter_campaigns enable row level security;
alter table public.blog_newsletter_deliveries enable row level security;

-- Clear older policy names so reruns stay safe.
drop policy if exists "Allow internal insert" on public.portfolio_messages;
drop policy if exists "Allow internal select" on public.portfolio_messages;
drop policy if exists "Allow internal delete" on public.portfolio_messages;
drop policy if exists "Enable insert for everyone" on public.portfolio_messages;
drop policy if exists "Enable read access for authenticated users only" on public.portfolio_messages;
drop policy if exists "Enable delete access for authenticated users only" on public.portfolio_messages;
drop policy if exists "portfolio_messages_public_insert" on public.portfolio_messages;
drop policy if exists "portfolio_messages_authenticated_select" on public.portfolio_messages;
drop policy if exists "portfolio_messages_authenticated_delete" on public.portfolio_messages;

drop policy if exists "Allow select for authenticated users" on public.portfolio_notes;
drop policy if exists "Allow insert for authenticated users" on public.portfolio_notes;
drop policy if exists "Allow delete for authenticated users" on public.portfolio_notes;
drop policy if exists "Allow update for authenticated users" on public.portfolio_notes;
drop policy if exists "portfolio_notes_authenticated_select" on public.portfolio_notes;
drop policy if exists "portfolio_notes_authenticated_insert" on public.portfolio_notes;
drop policy if exists "portfolio_notes_authenticated_update" on public.portfolio_notes;
drop policy if exists "portfolio_notes_authenticated_delete" on public.portfolio_notes;

drop policy if exists "Allow select for authenticated users" on public.portfolio_deadlines;
drop policy if exists "Allow insert for authenticated users" on public.portfolio_deadlines;
drop policy if exists "Allow delete for authenticated users" on public.portfolio_deadlines;
drop policy if exists "Allow update for authenticated users" on public.portfolio_deadlines;
drop policy if exists "portfolio_deadlines_authenticated_select" on public.portfolio_deadlines;
drop policy if exists "portfolio_deadlines_authenticated_insert" on public.portfolio_deadlines;
drop policy if exists "portfolio_deadlines_authenticated_update" on public.portfolio_deadlines;
drop policy if exists "portfolio_deadlines_authenticated_delete" on public.portfolio_deadlines;

drop policy if exists "Enable insert for everyone on blog_subscribers" on public.blog_subscribers;
drop policy if exists "Enable read access for authenticated users on blog_subscribers" on public.blog_subscribers;
drop policy if exists "Enable update for authenticated users on blog_subscribers" on public.blog_subscribers;
drop policy if exists "Enable delete for authenticated users on blog_subscribers" on public.blog_subscribers;
drop policy if exists "blog_subscribers_public_insert" on public.blog_subscribers;
drop policy if exists "blog_subscribers_authenticated_select" on public.blog_subscribers;
drop policy if exists "blog_subscribers_authenticated_update" on public.blog_subscribers;
drop policy if exists "blog_subscribers_authenticated_delete" on public.blog_subscribers;
drop policy if exists "blog_newsletter_campaigns_authenticated_select" on public.blog_newsletter_campaigns;
drop policy if exists "blog_newsletter_campaigns_service_role_insert" on public.blog_newsletter_campaigns;
drop policy if exists "blog_newsletter_campaigns_service_role_update" on public.blog_newsletter_campaigns;
drop policy if exists "blog_newsletter_campaigns_service_role_delete" on public.blog_newsletter_campaigns;
drop policy if exists "blog_newsletter_deliveries_authenticated_select" on public.blog_newsletter_deliveries;
drop policy if exists "blog_newsletter_deliveries_service_role_insert" on public.blog_newsletter_deliveries;
drop policy if exists "blog_newsletter_deliveries_service_role_update" on public.blog_newsletter_deliveries;
drop policy if exists "blog_newsletter_deliveries_service_role_delete" on public.blog_newsletter_deliveries;

create policy "portfolio_messages_public_insert"
on public.portfolio_messages
for insert
to public
with check (true);

create policy "portfolio_messages_authenticated_select"
on public.portfolio_messages
for select
to authenticated
using (true);

create policy "portfolio_messages_authenticated_delete"
on public.portfolio_messages
for delete
to authenticated
using (true);

create policy "portfolio_notes_authenticated_select"
on public.portfolio_notes
for select
to authenticated
using (true);

create policy "portfolio_notes_authenticated_insert"
on public.portfolio_notes
for insert
to authenticated
with check (true);

create policy "portfolio_notes_authenticated_update"
on public.portfolio_notes
for update
to authenticated
using (true)
with check (true);

create policy "portfolio_notes_authenticated_delete"
on public.portfolio_notes
for delete
to authenticated
using (true);

create policy "portfolio_deadlines_authenticated_select"
on public.portfolio_deadlines
for select
to authenticated
using (true);

create policy "portfolio_deadlines_authenticated_insert"
on public.portfolio_deadlines
for insert
to authenticated
with check (true);

create policy "portfolio_deadlines_authenticated_update"
on public.portfolio_deadlines
for update
to authenticated
using (true)
with check (true);

create policy "portfolio_deadlines_authenticated_delete"
on public.portfolio_deadlines
for delete
to authenticated
using (true);

create policy "blog_subscribers_public_insert"
on public.blog_subscribers
for insert
to public
with check (true);

create policy "blog_subscribers_authenticated_select"
on public.blog_subscribers
for select
to authenticated
using (true);

create policy "blog_subscribers_authenticated_update"
on public.blog_subscribers
for update
to authenticated
using (true)
with check (true);

create policy "blog_subscribers_authenticated_delete"
on public.blog_subscribers
for delete
to authenticated
using (true);

create policy "blog_newsletter_campaigns_authenticated_select"
on public.blog_newsletter_campaigns
for select
to authenticated
using (true);

create policy "blog_newsletter_campaigns_service_role_insert"
on public.blog_newsletter_campaigns
for insert
to service_role
with check (true);

create policy "blog_newsletter_campaigns_service_role_update"
on public.blog_newsletter_campaigns
for update
to service_role
using (true)
with check (true);

create policy "blog_newsletter_campaigns_service_role_delete"
on public.blog_newsletter_campaigns
for delete
to service_role
using (true);

create policy "blog_newsletter_deliveries_authenticated_select"
on public.blog_newsletter_deliveries
for select
to authenticated
using (true);

create policy "blog_newsletter_deliveries_service_role_insert"
on public.blog_newsletter_deliveries
for insert
to service_role
with check (true);

create policy "blog_newsletter_deliveries_service_role_update"
on public.blog_newsletter_deliveries
for update
to service_role
using (true)
with check (true);

create policy "blog_newsletter_deliveries_service_role_delete"
on public.blog_newsletter_deliveries
for delete
to service_role
using (true);

commit;
