-- ==========================================
-- SUPABASE PORTFOLIO SETUP SCRIPT
-- ==========================================

-- 1. Create the portfolio_messages table
create table if not exists public.portfolio_messages (
  id bigint generated by default as identity primary key,
  content text not null,
  timestamp text,
  user_agent text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Enable Row Level Security (RLS)
alter table public.portfolio_messages enable row level security;

-- 3. Policy: Allow anyone to send messages (Contact Form)
create policy "Allow internal insert"
on public.portfolio_messages
for insert
to anon
with check (true);

-- 4. Policy: Allow viewing messages (Admin Dashboard)
create policy "Allow internal select"
on public.portfolio_messages
for select
to anon
using (true);

-- 5. Policy: Allow deleting messages (Admin Dashboard)
create policy "Allow internal delete"
on public.portfolio_messages
for delete
to anon
using (true);