-- Create Notes Table
CREATE TABLE public.portfolio_notes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Create Deadlines Table
CREATE TABLE public.portfolio_deadlines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description TEXT NOT NULL,
    deadline_date DATE NOT NULL,
    deadline_time TIME WITHOUT TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.portfolio_notes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.portfolio_deadlines ENABLE ROW LEVEL SECURITY;

-- Policies for portfolio_notes: Only authenticated users can manage notes
CREATE POLICY "Allow select for authenticated users" ON public.portfolio_notes FOR SELECT TO authenticated USING (true);
CREATE POLICY "Allow insert for authenticated users" ON public.portfolio_notes FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Allow delete for authenticated users" ON public.portfolio_notes FOR DELETE TO authenticated USING (true);
CREATE POLICY "Allow update for authenticated users" ON public.portfolio_notes FOR UPDATE TO authenticated USING (true);

-- Policies for portfolio_deadlines: Only authenticated users can manage deadlines
CREATE POLICY "Allow select for authenticated users" ON public.portfolio_deadlines FOR SELECT TO authenticated USING (true);
CREATE POLICY "Allow insert for authenticated users" ON public.portfolio_deadlines FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Allow delete for authenticated users" ON public.portfolio_deadlines FOR DELETE TO authenticated USING (true);
CREATE POLICY "Allow update for authenticated users" ON public.portfolio_deadlines FOR UPDATE TO authenticated USING (true);
